#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

log_emails=$(git config user.email)

if [[ ${log_emails} == *"@gmail.com" || ${log_emails} == *"@qq.com" ]];then
  echo 邮箱 $log_emails 校验通过
else
  echo 本地提交邮箱 $log_emails 校验非法，需要本地更改重新提交。仅支持 @gmail.com 或 @qq.com 邮箱
  exit 2;
fi
